framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr_FR
    csrf_protection: ~
    http_method_override: true
    trusted_hosts: ~

    session:
        handler_id: ~

    #esi: ~
    fragments: ~
    php_errors:
        log: true
