branches:
  only:
    - master
    - dev
    - /^[0-9]+\.[0-9]+$/

env:
  - APP_ENV="test" APP_SECRET="6044a41cfb95fb92a92c293a84e1601d27740171" DATABASE_URL="mysql://travis@127.0.0.1/akisroc"

dist: trusty
language: php
php:
  - '7.4'

services:
  - mysql

addons:
  mariadb: '10.4.12'

before_install:
  - n=$(git log --oneline | grep "fixup!" | wc -l); if [[ $n == 0 ]]; then echo "OK\n"; else echo "Error - $n remaining fixup(s)\n" && exit 1; fi
  - mysql -e 'CREATE DATABASE akisroc;'
  - git clone -b stable https://github.com/jedisct1/libsodium.git
  - cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
  - composer self-update
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y

install:
  - pecl install libsodium
  - echo "extension=sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install
  - git submodule update --init
  - npm install
  - npm run dev

before_script:
  - printf "adminus\nadminus@adminus.test\nadminus\nhttp://nsa39.casimages.com/img/2018/01/02/180102012113625901.jpg" > ./src/DataFixtures/Prod/.apwd
  - php bin/console doctrine:schema:create
  - php bin/console doctrine:fixtures:load --no-interaction
  - php -S 127.0.0.1:8000 -t public/ &

scripts:
  - php bin/phpunit tests/
  - ./vendor/bin/phpstan analyse src/ --level max
