branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+$/

env:
  - APP_ENV="dev" APP_SECRET="6044a41cfb95fb92a92c293a84e1601d27740171" DATABASE_URL="mysql://travis@127.0.0.1/akisroc"

language: php
php:
  - '7.2'

services:
  - mysql

addons:
  mariadb: '10.0'

before_install:
  - mysql -e 'CREATE DATABASE akisroc;'

install:
  - composer install
  - composer require paragonie/sodium_compat
  - npm install
  - ./node_modules/.bin/encore dev

before_script:
#  - docker-compose up -d
  - php bin/console doctrine:schema:create
  - php bin/console doctrine:fixtures:load --no-interaction
  - php bin/console server:start

script: ./vendor/bin/phpunit tests/