version: '2'

services:

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: akisroc
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080