version: '3.2'

services:

  database:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: akisroc
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
    - ./database:/var/lib/mysql

  http:
    image: nginx:1-alpine
    depends_on:
      - php
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/:/srv/public/:ro
    ports:
      - 8000:80

  php:
    build: ./docker/php
    working_dir: /srv
    volumes:
    - ./:/srv/

  node:
    build: ./docker/node
    working_dir: /srv
    volumes:
    - ./:/srv/

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  database: ~
